site_name: Анализ ошибок датасета

theme:
  name: material

nav:
  - Главная: index.md
  - О проекте: about.md
  - Ход работы: progress.md
  - Анализ датасета: analysis.md
  - Графики: graphs.md
  - Выводы: results.md

markdown_extensions:
  - tables
  - toc
  - admonition
  - codehilite