site_name: Анализ ошибок датасета

theme:
  name: material

extra:
  alternate:
    - name: Русский
      link: /dataset/
      lang: ru
    - name: English
      link: /dataset/en/
      lang: en

plugins:
  - search
  - i18n:
      default_language: ru
      languages:
        ru:
          name: Русский
          build: true
        en:
          name: English
          build: true

nav:
  - Главная: index.md
  - О проекте: about.md
  - Ход работы: progress.md
  - Анализ датасета: analysis.md
  - Графики: graphs.md
  - Выводы: results.md

markdown_extensions:
  - tables
  - toc
  - admonition
  - codehilite
