site_name: Анализ ошибок датасета

theme:
  name: material
  features:
    - navigation.footer

extra:
  alternate:
    - name: Русский
      link: ""
      lang: ru
    - name: English
      link: "en/"
      lang: en

plugins:
  - search
  - i18n:
      default_language: ru
      languages:
        - locale: ru
          name: Русский
          default: true
        - locale: en
          name: English
          nav:
            - "Главная": "Home"
            - "О проекте": "About"
            - "Ход работы": "Progress"
            - "Анализ датасета": "Dataset Analysis"
            - "Графики": "Graphs"
            - "Выводы": "Conclusions"

nav:
  - Главная: index.md
  - О проекте: about.md
  - Ход работы: progress.md
  - Анализ датасета: analysis.md
  - Графики: graphs.md
  - Выводы: results.md

markdown_extensions:
  - tables
  - toc
  - admonition
  - codehilite
